# adjoint source type
adj_src_type: "multitaper_misfit"

# min and max period(unit: second)
min_period: 50.0
max_period: 100.0

# adjoint config parameter
lnpt: 15
transfunc_waterlevel: 1.0E-10
ipower_costaper: 10
min_cycle_in_window: 3
taper_percentage: 0.3
mt_nw: 4.0
num_taper: 5
phase_step: 1.5
dt_fac: 2.0
err_fac: 2.5
dt_max_scale: 3.5
measure_type: 'dt'
taper_type: 'hann'
use_cc_error: True
use_mt_error: False

# for postprocessing
interp_delta: 0.1425
interp_npts: 42000
